/* Generated by Yosys 0.48 (git sha1 aaa5347494801e9e3870b31387da59da24233f76, x86_64-w64-mingw32-g++ 13.2.0 -O3 -DNDEBUG) */

module adc045_wrap(clk, rst_l, drdy, dout, cs, din, sclk, nRST, start, hard_start, hard_wreg, rst_l_adc, ready_sample, adc045_data);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  output [23:0] adc045_data;
  wire [23:0] adc045_data;
  wire \adc_rd.bit_cnt[0] ;
  wire \adc_rd.bit_cnt[1] ;
  wire \adc_rd.bit_cnt[2] ;
  wire \adc_rd.bit_cnt[3] ;
  wire \adc_rd.bit_cnt[4] ;
  wire \adc_rd.bit_cnt[5] ;
  wire \adc_rd.ch1_acc[0] ;
  wire \adc_rd.ch1_acc[10] ;
  wire \adc_rd.ch1_acc[11] ;
  wire \adc_rd.ch1_acc[12] ;
  wire \adc_rd.ch1_acc[13] ;
  wire \adc_rd.ch1_acc[14] ;
  wire \adc_rd.ch1_acc[15] ;
  wire \adc_rd.ch1_acc[16] ;
  wire \adc_rd.ch1_acc[17] ;
  wire \adc_rd.ch1_acc[18] ;
  wire \adc_rd.ch1_acc[19] ;
  wire \adc_rd.ch1_acc[1] ;
  wire \adc_rd.ch1_acc[20] ;
  wire \adc_rd.ch1_acc[21] ;
  wire \adc_rd.ch1_acc[22] ;
  wire \adc_rd.ch1_acc[23] ;
  wire \adc_rd.ch1_acc[2] ;
  wire \adc_rd.ch1_acc[3] ;
  wire \adc_rd.ch1_acc[4] ;
  wire \adc_rd.ch1_acc[5] ;
  wire \adc_rd.ch1_acc[6] ;
  wire \adc_rd.ch1_acc[7] ;
  wire \adc_rd.ch1_acc[8] ;
  wire \adc_rd.ch1_acc[9] ;
  wire \adc_rd.ch1_prev[0] ;
  wire \adc_rd.ch1_prev[10] ;
  wire \adc_rd.ch1_prev[11] ;
  wire \adc_rd.ch1_prev[12] ;
  wire \adc_rd.ch1_prev[13] ;
  wire \adc_rd.ch1_prev[14] ;
  wire \adc_rd.ch1_prev[15] ;
  wire \adc_rd.ch1_prev[16] ;
  wire \adc_rd.ch1_prev[17] ;
  wire \adc_rd.ch1_prev[18] ;
  wire \adc_rd.ch1_prev[19] ;
  wire \adc_rd.ch1_prev[1] ;
  wire \adc_rd.ch1_prev[20] ;
  wire \adc_rd.ch1_prev[21] ;
  wire \adc_rd.ch1_prev[22] ;
  wire \adc_rd.ch1_prev[23] ;
  wire \adc_rd.ch1_prev[2] ;
  wire \adc_rd.ch1_prev[3] ;
  wire \adc_rd.ch1_prev[4] ;
  wire \adc_rd.ch1_prev[5] ;
  wire \adc_rd.ch1_prev[6] ;
  wire \adc_rd.ch1_prev[7] ;
  wire \adc_rd.ch1_prev[8] ;
  wire \adc_rd.ch1_prev[9] ;
  wire \adc_rd.shift_reg[0] ;
  wire \adc_rd.shift_reg[10] ;
  wire \adc_rd.shift_reg[11] ;
  wire \adc_rd.shift_reg[12] ;
  wire \adc_rd.shift_reg[13] ;
  wire \adc_rd.shift_reg[14] ;
  wire \adc_rd.shift_reg[15] ;
  wire \adc_rd.shift_reg[16] ;
  wire \adc_rd.shift_reg[17] ;
  wire \adc_rd.shift_reg[18] ;
  wire \adc_rd.shift_reg[19] ;
  wire \adc_rd.shift_reg[1] ;
  wire \adc_rd.shift_reg[20] ;
  wire \adc_rd.shift_reg[21] ;
  wire \adc_rd.shift_reg[22] ;
  wire \adc_rd.shift_reg[23] ;
  wire \adc_rd.shift_reg[2] ;
  wire \adc_rd.shift_reg[3] ;
  wire \adc_rd.shift_reg[4] ;
  wire \adc_rd.shift_reg[5] ;
  wire \adc_rd.shift_reg[6] ;
  wire \adc_rd.shift_reg[7] ;
  wire \adc_rd.shift_reg[8] ;
  wire \adc_rd.shift_reg[9] ;
  wire \adc_rd.start_mode ;
  wire \adc_rd.state[0] ;
  wire \adc_rd.state[1] ;
  wire \adc_rd.state[2] ;
  wire \adc_rd.work_mode ;
  wire \adc_rd.wreg_mode ;
  input clk;
  wire clk;
  input cs;
  wire cs;
  output din;
  wire din;
  input dout;
  wire dout;
  input drdy;
  wire drdy;
  input hard_start;
  wire hard_start;
  input hard_wreg;
  wire hard_wreg;
  output nRST;
  wire nRST;
  output ready_sample;
  wire ready_sample;
  input rst_l;
  wire rst_l;
  input rst_l_adc;
  wire rst_l_adc;
  output sclk;
  wire sclk;
  output start;
  wire start;
  xci2_inv _184_ (
    .a(sclk),
    .y(_062_)
  );
  xci2_and2ft _185_ (
    .a(drdy),
    .b(\adc_rd.work_mode ),
    .y(_063_)
  );
  xci2_and3ftt _186_ (
    .a(drdy),
    .b(dout),
    .c(\adc_rd.work_mode ),
    .y(_064_)
  );
  xci2_nor2 _187_ (
    .a(\adc_rd.bit_cnt[2] ),
    .b(\adc_rd.bit_cnt[5] ),
    .y(_065_)
  );
  xci2_and2ft _188_ (
    .a(\adc_rd.bit_cnt[1] ),
    .b(\adc_rd.bit_cnt[0] ),
    .y(_066_)
  );
  xci2_and3fft _189_ (
    .a(\adc_rd.bit_cnt[1] ),
    .b(\adc_rd.bit_cnt[2] ),
    .c(\adc_rd.bit_cnt[0] ),
    .y(_067_)
  );
  xci2_or3 _190_ (
    .a(\adc_rd.bit_cnt[3] ),
    .b(\adc_rd.bit_cnt[4] ),
    .c(\adc_rd.bit_cnt[5] ),
    .y(_068_)
  );
  xci2_nor2ft _191_ (
    .a(_067_),
    .b(_068_),
    .y(_069_)
  );
  xci2_or3fft _192_ (
    .a(\adc_rd.start_mode ),
    .b(_067_),
    .c(_068_),
    .y(_070_)
  );
  xci2_or2 _193_ (
    .a(\adc_rd.wreg_mode ),
    .b(\adc_rd.start_mode ),
    .y(_071_)
  );
  xci2_nor3 _194_ (
    .a(\adc_rd.wreg_mode ),
    .b(\adc_rd.work_mode ),
    .c(\adc_rd.start_mode ),
    .y(_072_)
  );
  xci2_oa21ttf _195_ (
    .a(\adc_rd.wreg_mode ),
    .b(\adc_rd.start_mode ),
    .c(\adc_rd.work_mode ),
    .y(_073_)
  );
  xci2_aoi21 _196_ (
    .a(\adc_rd.shift_reg[0] ),
    .b(_072_),
    .c(_064_),
    .y(_074_)
  );
  xci2_oai21 _197_ (
    .a(\adc_rd.work_mode ),
    .b(_070_),
    .c(_074_),
    .y(_000_)
  );
  xci2_ao21ftt _198_ (
    .a(_069_),
    .b(_071_),
    .c(\adc_rd.work_mode ),
    .y(_075_)
  );
  xci2_nand2 _199_ (
    .a(\adc_rd.work_mode ),
    .b(drdy),
    .y(_076_)
  );
  xci2_and3 _200_ (
    .a(\adc_rd.shift_reg[0] ),
    .b(_075_),
    .c(_076_),
    .y(_077_)
  );
  xci2_ao21 _201_ (
    .a(\adc_rd.shift_reg[1] ),
    .b(_072_),
    .c(_077_),
    .y(_001_)
  );
  xci2_and3 _202_ (
    .a(\adc_rd.shift_reg[1] ),
    .b(_075_),
    .c(_076_),
    .y(_078_)
  );
  xci2_ao21 _203_ (
    .a(\adc_rd.shift_reg[2] ),
    .b(_072_),
    .c(_078_),
    .y(_002_)
  );
  xci2_and3 _204_ (
    .a(\adc_rd.shift_reg[2] ),
    .b(_075_),
    .c(_076_),
    .y(_079_)
  );
  xci2_ao21 _205_ (
    .a(\adc_rd.shift_reg[3] ),
    .b(_072_),
    .c(_079_),
    .y(_003_)
  );
  xci2_and3 _206_ (
    .a(\adc_rd.shift_reg[3] ),
    .b(_075_),
    .c(_076_),
    .y(_080_)
  );
  xci2_ao21 _207_ (
    .a(\adc_rd.shift_reg[4] ),
    .b(_072_),
    .c(_080_),
    .y(_004_)
  );
  xci2_and3 _208_ (
    .a(\adc_rd.shift_reg[4] ),
    .b(_075_),
    .c(_076_),
    .y(_081_)
  );
  xci2_ao21 _209_ (
    .a(\adc_rd.shift_reg[5] ),
    .b(_072_),
    .c(_081_),
    .y(_005_)
  );
  xci2_and3 _210_ (
    .a(\adc_rd.shift_reg[5] ),
    .b(_075_),
    .c(_076_),
    .y(_082_)
  );
  xci2_ao21 _211_ (
    .a(\adc_rd.shift_reg[6] ),
    .b(_072_),
    .c(_082_),
    .y(_006_)
  );
  xci2_and3 _212_ (
    .a(\adc_rd.shift_reg[6] ),
    .b(_075_),
    .c(_076_),
    .y(_083_)
  );
  xci2_ao21 _213_ (
    .a(\adc_rd.shift_reg[7] ),
    .b(_072_),
    .c(_083_),
    .y(_007_)
  );
  xci2_and3 _214_ (
    .a(\adc_rd.shift_reg[7] ),
    .b(_075_),
    .c(_076_),
    .y(_084_)
  );
  xci2_ao21 _215_ (
    .a(\adc_rd.shift_reg[8] ),
    .b(_072_),
    .c(_084_),
    .y(_008_)
  );
  xci2_and3 _216_ (
    .a(\adc_rd.shift_reg[8] ),
    .b(_075_),
    .c(_076_),
    .y(_085_)
  );
  xci2_ao21 _217_ (
    .a(\adc_rd.shift_reg[9] ),
    .b(_072_),
    .c(_085_),
    .y(_009_)
  );
  xci2_and3 _218_ (
    .a(\adc_rd.shift_reg[9] ),
    .b(_075_),
    .c(_076_),
    .y(_086_)
  );
  xci2_ao21 _219_ (
    .a(\adc_rd.shift_reg[10] ),
    .b(_072_),
    .c(_086_),
    .y(_010_)
  );
  xci2_and3 _220_ (
    .a(\adc_rd.shift_reg[10] ),
    .b(_075_),
    .c(_076_),
    .y(_087_)
  );
  xci2_ao21 _221_ (
    .a(\adc_rd.shift_reg[11] ),
    .b(_072_),
    .c(_087_),
    .y(_011_)
  );
  xci2_and3 _222_ (
    .a(\adc_rd.shift_reg[11] ),
    .b(_075_),
    .c(_076_),
    .y(_088_)
  );
  xci2_ao21 _223_ (
    .a(\adc_rd.shift_reg[12] ),
    .b(_072_),
    .c(_088_),
    .y(_012_)
  );
  xci2_and3 _224_ (
    .a(\adc_rd.shift_reg[12] ),
    .b(_075_),
    .c(_076_),
    .y(_089_)
  );
  xci2_ao21 _225_ (
    .a(\adc_rd.shift_reg[13] ),
    .b(_072_),
    .c(_089_),
    .y(_013_)
  );
  xci2_and3 _226_ (
    .a(\adc_rd.shift_reg[13] ),
    .b(_075_),
    .c(_076_),
    .y(_090_)
  );
  xci2_ao21 _227_ (
    .a(\adc_rd.shift_reg[14] ),
    .b(_072_),
    .c(_090_),
    .y(_014_)
  );
  xci2_and3 _228_ (
    .a(\adc_rd.shift_reg[14] ),
    .b(_075_),
    .c(_076_),
    .y(_091_)
  );
  xci2_ao21 _229_ (
    .a(\adc_rd.shift_reg[15] ),
    .b(_072_),
    .c(_091_),
    .y(_015_)
  );
  xci2_and3 _230_ (
    .a(\adc_rd.shift_reg[15] ),
    .b(_075_),
    .c(_076_),
    .y(_092_)
  );
  xci2_ao21 _231_ (
    .a(\adc_rd.shift_reg[16] ),
    .b(_072_),
    .c(_092_),
    .y(_016_)
  );
  xci2_and3 _232_ (
    .a(\adc_rd.shift_reg[16] ),
    .b(_075_),
    .c(_076_),
    .y(_093_)
  );
  xci2_ao21 _233_ (
    .a(\adc_rd.shift_reg[17] ),
    .b(_072_),
    .c(_093_),
    .y(_017_)
  );
  xci2_ao21 _234_ (
    .a(_070_),
    .b(_073_),
    .c(_063_),
    .y(_094_)
  );
  xci2_nand3ftt _235_ (
    .a(\adc_rd.start_mode ),
    .b(_069_),
    .c(_073_),
    .y(_095_)
  );
  xci2_ao21ttf _236_ (
    .a(\adc_rd.shift_reg[17] ),
    .b(_094_),
    .c(_095_),
    .y(_096_)
  );
  xci2_ao21 _237_ (
    .a(\adc_rd.shift_reg[18] ),
    .b(_072_),
    .c(_096_),
    .y(_018_)
  );
  xci2_and3ftt _238_ (
    .a(drdy),
    .b(\adc_rd.work_mode ),
    .c(\adc_rd.shift_reg[18] ),
    .y(_097_)
  );
  xci2_mux2h _239_ (
    .a(\adc_rd.shift_reg[18] ),
    .b(\adc_rd.start_mode ),
    .s(_069_),
    .y(_098_)
  );
  xci2_ao21 _240_ (
    .a(_073_),
    .b(_098_),
    .c(_097_),
    .y(_099_)
  );
  xci2_ao21 _241_ (
    .a(\adc_rd.shift_reg[19] ),
    .b(_072_),
    .c(_099_),
    .y(_019_)
  );
  xci2_ao21ttf _242_ (
    .a(\adc_rd.shift_reg[19] ),
    .b(_094_),
    .c(_095_),
    .y(_100_)
  );
  xci2_ao21 _243_ (
    .a(\adc_rd.shift_reg[20] ),
    .b(_072_),
    .c(_100_),
    .y(_020_)
  );
  xci2_and3 _244_ (
    .a(\adc_rd.shift_reg[20] ),
    .b(_075_),
    .c(_076_),
    .y(_101_)
  );
  xci2_ao21 _245_ (
    .a(\adc_rd.shift_reg[21] ),
    .b(_072_),
    .c(_101_),
    .y(_021_)
  );
  xci2_and3 _246_ (
    .a(\adc_rd.shift_reg[21] ),
    .b(_075_),
    .c(_076_),
    .y(_102_)
  );
  xci2_ao21 _247_ (
    .a(\adc_rd.shift_reg[22] ),
    .b(_072_),
    .c(_102_),
    .y(_022_)
  );
  xci2_and3ftt _248_ (
    .a(drdy),
    .b(\adc_rd.work_mode ),
    .c(\adc_rd.shift_reg[22] ),
    .y(_103_)
  );
  xci2_mux2h _249_ (
    .a(\adc_rd.shift_reg[22] ),
    .b(\adc_rd.start_mode ),
    .s(_069_),
    .y(_104_)
  );
  xci2_ao21 _250_ (
    .a(_073_),
    .b(_104_),
    .c(_103_),
    .y(_105_)
  );
  xci2_ao21 _251_ (
    .a(\adc_rd.shift_reg[23] ),
    .b(_072_),
    .c(_105_),
    .y(_023_)
  );
  xci2_and3fft _252_ (
    .a(\adc_rd.state[2] ),
    .b(cs),
    .c(\adc_rd.state[1] ),
    .y(_106_)
  );
  xci2_nand3fft _253_ (
    .a(\adc_rd.state[2] ),
    .b(cs),
    .c(\adc_rd.state[1] ),
    .y(_107_)
  );
  xci2_nor2 _254_ (
    .a(\adc_rd.state[1] ),
    .b(cs),
    .y(_108_)
  );
  xci2_nand3ftt _255_ (
    .a(\adc_rd.state[0] ),
    .b(\adc_rd.state[2] ),
    .c(_108_),
    .y(_109_)
  );
  xci2_and2ft _256_ (
    .a(\adc_rd.bit_cnt[0] ),
    .b(\adc_rd.bit_cnt[1] ),
    .y(_110_)
  );
  xci2_and2 _257_ (
    .a(\adc_rd.bit_cnt[3] ),
    .b(\adc_rd.bit_cnt[4] ),
    .y(_111_)
  );
  xci2_nand3 _258_ (
    .a(_065_),
    .b(_110_),
    .c(_111_),
    .y(_112_)
  );
  xci2_nand2ft _259_ (
    .a(_109_),
    .b(_112_),
    .y(_113_)
  );
  xci2_ao21ftf _260_ (
    .a(_109_),
    .b(_112_),
    .c(_107_),
    .y(_114_)
  );
  xci2_and2 _261_ (
    .a(_107_),
    .b(_109_),
    .y(_115_)
  );
  xci2_mux2h _262_ (
    .a(_114_),
    .b(_115_),
    .s(\adc_rd.bit_cnt[0] ),
    .y(_024_)
  );
  xci2_xnor2 _263_ (
    .a(\adc_rd.bit_cnt[0] ),
    .b(\adc_rd.bit_cnt[1] ),
    .y(_116_)
  );
  xci2_and3 _264_ (
    .a(_065_),
    .b(_066_),
    .c(_111_),
    .y(_117_)
  );
  xci2_nand3fft _265_ (
    .a(_117_),
    .b(_107_),
    .c(\adc_rd.state[0] ),
    .y(_118_)
  );
  xci2_ao21 _266_ (
    .a(\adc_rd.state[0] ),
    .b(_117_),
    .c(_107_),
    .y(_119_)
  );
  xci2_aoi21 _267_ (
    .a(_113_),
    .b(_119_),
    .c(_116_),
    .y(_120_)
  );
  xci2_ao21 _268_ (
    .a(\adc_rd.bit_cnt[1] ),
    .b(_115_),
    .c(_120_),
    .y(_025_)
  );
  xci2_nand3ftt _269_ (
    .a(_115_),
    .b(\adc_rd.bit_cnt[1] ),
    .c(\adc_rd.bit_cnt[0] ),
    .y(_121_)
  );
  xci2_xnor2 _270_ (
    .a(\adc_rd.bit_cnt[2] ),
    .b(_121_),
    .y(_026_)
  );
  xci2_and3 _271_ (
    .a(\adc_rd.bit_cnt[3] ),
    .b(_107_),
    .c(_109_),
    .y(_122_)
  );
  xci2_and3 _272_ (
    .a(\adc_rd.bit_cnt[0] ),
    .b(\adc_rd.bit_cnt[1] ),
    .c(\adc_rd.bit_cnt[2] ),
    .y(_123_)
  );
  xci2_and3fft _273_ (
    .a(\adc_rd.bit_cnt[3] ),
    .b(\adc_rd.bit_cnt[5] ),
    .c(\adc_rd.bit_cnt[4] ),
    .y(_124_)
  );
  xci2_nand2 _274_ (
    .a(_123_),
    .b(_124_),
    .y(_125_)
  );
  xci2_nand3fft _275_ (
    .a(\adc_rd.state[0] ),
    .b(_107_),
    .c(_125_),
    .y(_126_)
  );
  xci2_nand2 _276_ (
    .a(_118_),
    .b(_126_),
    .y(_127_)
  );
  xci2_nand3 _277_ (
    .a(_113_),
    .b(_118_),
    .c(_126_),
    .y(_128_)
  );
  xci2_and2 _278_ (
    .a(\adc_rd.bit_cnt[3] ),
    .b(_123_),
    .y(_129_)
  );
  xci2_xnor2ft _279_ (
    .a(\adc_rd.bit_cnt[3] ),
    .b(_123_),
    .y(_130_)
  );
  xci2_ao21 _280_ (
    .a(_128_),
    .b(_130_),
    .c(_122_),
    .y(_027_)
  );
  xci2_and3 _281_ (
    .a(\adc_rd.bit_cnt[4] ),
    .b(_107_),
    .c(_109_),
    .y(_131_)
  );
  xci2_xnor2ft _282_ (
    .a(\adc_rd.bit_cnt[4] ),
    .b(_129_),
    .y(_132_)
  );
  xci2_ao21 _283_ (
    .a(_128_),
    .b(_132_),
    .c(_131_),
    .y(_028_)
  );
  xci2_nand3ftt _284_ (
    .a(_115_),
    .b(_129_),
    .c(\adc_rd.bit_cnt[4] ),
    .y(_133_)
  );
  xci2_xnor2 _285_ (
    .a(\adc_rd.bit_cnt[5] ),
    .b(_133_),
    .y(_029_)
  );
  xci2_ao21 _286_ (
    .a(\adc_rd.wreg_mode ),
    .b(_107_),
    .c(_127_),
    .y(_030_)
  );
  xci2_nand3ftt _287_ (
    .a(_069_),
    .b(_071_),
    .c(rst_l),
    .y(_134_)
  );
  xci2_mux2h _288_ (
    .a(\adc_rd.shift_reg[23] ),
    .b(din),
    .s(_134_),
    .y(_031_)
  );
  xci2_and3fft _289_ (
    .a(\adc_rd.state[1] ),
    .b(cs),
    .c(\adc_rd.state[0] ),
    .y(_135_)
  );
  xci2_and2 _290_ (
    .a(\adc_rd.state[2] ),
    .b(_135_),
    .y(_136_)
  );
  xci2_and3fft _291_ (
    .a(\adc_rd.state[2] ),
    .b(hard_wreg),
    .c(_135_),
    .y(_137_)
  );
  xci2_nand3fft _292_ (
    .a(\adc_rd.state[0] ),
    .b(\adc_rd.state[2] ),
    .c(_108_),
    .y(_138_)
  );
  xci2_and3fft _293_ (
    .a(_136_),
    .b(_137_),
    .c(_138_),
    .y(_139_)
  );
  xci2_nand3fft _294_ (
    .a(_125_),
    .b(\adc_rd.state[0] ),
    .c(_106_),
    .y(_140_)
  );
  xci2_oa21 _295_ (
    .a(_109_),
    .b(_112_),
    .c(_118_),
    .y(_141_)
  );
  xci2_nand3 _296_ (
    .a(_139_),
    .b(_140_),
    .c(_141_),
    .y(_032_)
  );
  xci2_and3ftt _297_ (
    .a(\adc_rd.state[2] ),
    .b(hard_wreg),
    .c(_135_),
    .y(_142_)
  );
  xci2_nand3fft _298_ (
    .a(_142_),
    .b(_127_),
    .c(_138_),
    .y(_033_)
  );
  xci2_and3 _299_ (
    .a(\adc_rd.state[2] ),
    .b(rst_l_adc),
    .c(_135_),
    .y(_143_)
  );
  xci2_nand3 _300_ (
    .a(\adc_rd.state[0] ),
    .b(_106_),
    .c(_117_),
    .y(_144_)
  );
  xci2_aoi21 _301_ (
    .a(hard_start),
    .b(_137_),
    .c(_143_),
    .y(_145_)
  );
  xci2_nand3 _302_ (
    .a(_109_),
    .b(_144_),
    .c(_145_),
    .y(_034_)
  );
  xci2_mux2h _303_ (
    .a(\adc_rd.work_mode ),
    .b(rst_l_adc),
    .s(_136_),
    .y(_035_)
  );
  xci2_mux2h _304_ (
    .a(\adc_rd.shift_reg[0] ),
    .b(\adc_rd.ch1_acc[0] ),
    .s(_076_),
    .y(_036_)
  );
  xci2_mux2h _305_ (
    .a(\adc_rd.shift_reg[1] ),
    .b(\adc_rd.ch1_acc[1] ),
    .s(_076_),
    .y(_037_)
  );
  xci2_mux2h _306_ (
    .a(\adc_rd.shift_reg[2] ),
    .b(\adc_rd.ch1_acc[2] ),
    .s(_076_),
    .y(_038_)
  );
  xci2_mux2h _307_ (
    .a(\adc_rd.shift_reg[3] ),
    .b(\adc_rd.ch1_acc[3] ),
    .s(_076_),
    .y(_039_)
  );
  xci2_mux2h _308_ (
    .a(\adc_rd.shift_reg[4] ),
    .b(\adc_rd.ch1_acc[4] ),
    .s(_076_),
    .y(_040_)
  );
  xci2_mux2h _309_ (
    .a(\adc_rd.shift_reg[5] ),
    .b(\adc_rd.ch1_acc[5] ),
    .s(_076_),
    .y(_041_)
  );
  xci2_mux2h _310_ (
    .a(\adc_rd.shift_reg[6] ),
    .b(\adc_rd.ch1_acc[6] ),
    .s(_076_),
    .y(_042_)
  );
  xci2_mux2h _311_ (
    .a(\adc_rd.shift_reg[7] ),
    .b(\adc_rd.ch1_acc[7] ),
    .s(_076_),
    .y(_043_)
  );
  xci2_mux2h _312_ (
    .a(\adc_rd.shift_reg[8] ),
    .b(\adc_rd.ch1_acc[8] ),
    .s(_076_),
    .y(_044_)
  );
  xci2_mux2h _313_ (
    .a(\adc_rd.shift_reg[9] ),
    .b(\adc_rd.ch1_acc[9] ),
    .s(_076_),
    .y(_045_)
  );
  xci2_mux2h _314_ (
    .a(\adc_rd.shift_reg[10] ),
    .b(\adc_rd.ch1_acc[10] ),
    .s(_076_),
    .y(_046_)
  );
  xci2_mux2h _315_ (
    .a(\adc_rd.shift_reg[11] ),
    .b(\adc_rd.ch1_acc[11] ),
    .s(_076_),
    .y(_047_)
  );
  xci2_mux2h _316_ (
    .a(\adc_rd.shift_reg[12] ),
    .b(\adc_rd.ch1_acc[12] ),
    .s(_076_),
    .y(_048_)
  );
  xci2_mux2h _317_ (
    .a(\adc_rd.shift_reg[13] ),
    .b(\adc_rd.ch1_acc[13] ),
    .s(_076_),
    .y(_049_)
  );
  xci2_mux2h _318_ (
    .a(\adc_rd.shift_reg[14] ),
    .b(\adc_rd.ch1_acc[14] ),
    .s(_076_),
    .y(_050_)
  );
  xci2_mux2h _319_ (
    .a(\adc_rd.shift_reg[15] ),
    .b(\adc_rd.ch1_acc[15] ),
    .s(_076_),
    .y(_051_)
  );
  xci2_mux2h _320_ (
    .a(\adc_rd.shift_reg[16] ),
    .b(\adc_rd.ch1_acc[16] ),
    .s(_076_),
    .y(_052_)
  );
  xci2_mux2h _321_ (
    .a(\adc_rd.shift_reg[17] ),
    .b(\adc_rd.ch1_acc[17] ),
    .s(_076_),
    .y(_053_)
  );
  xci2_mux2h _322_ (
    .a(\adc_rd.shift_reg[18] ),
    .b(\adc_rd.ch1_acc[18] ),
    .s(_076_),
    .y(_054_)
  );
  xci2_mux2h _323_ (
    .a(\adc_rd.shift_reg[19] ),
    .b(\adc_rd.ch1_acc[19] ),
    .s(_076_),
    .y(_055_)
  );
  xci2_mux2h _324_ (
    .a(\adc_rd.shift_reg[20] ),
    .b(\adc_rd.ch1_acc[20] ),
    .s(_076_),
    .y(_056_)
  );
  xci2_mux2h _325_ (
    .a(\adc_rd.shift_reg[21] ),
    .b(\adc_rd.ch1_acc[21] ),
    .s(_076_),
    .y(_057_)
  );
  xci2_mux2h _326_ (
    .a(\adc_rd.shift_reg[22] ),
    .b(\adc_rd.ch1_acc[22] ),
    .s(_076_),
    .y(_058_)
  );
  xci2_mux2h _327_ (
    .a(\adc_rd.shift_reg[23] ),
    .b(\adc_rd.ch1_acc[23] ),
    .s(_076_),
    .y(_059_)
  );
  xci2_mux2h _328_ (
    .a(_112_),
    .b(\adc_rd.start_mode ),
    .s(_109_),
    .y(_060_)
  );
  xci2_xnor2 _329_ (
    .a(\adc_rd.ch1_acc[15] ),
    .b(\adc_rd.ch1_prev[15] ),
    .y(_146_)
  );
  xci2_xnor2 _330_ (
    .a(\adc_rd.ch1_acc[22] ),
    .b(\adc_rd.ch1_prev[22] ),
    .y(_147_)
  );
  xci2_xnor2 _331_ (
    .a(\adc_rd.ch1_acc[2] ),
    .b(\adc_rd.ch1_prev[2] ),
    .y(_148_)
  );
  xci2_xnor2 _332_ (
    .a(\adc_rd.ch1_acc[0] ),
    .b(\adc_rd.ch1_prev[0] ),
    .y(_149_)
  );
  xci2_xnor2 _333_ (
    .a(\adc_rd.ch1_acc[14] ),
    .b(\adc_rd.ch1_prev[14] ),
    .y(_150_)
  );
  xci2_xnor2 _334_ (
    .a(\adc_rd.ch1_acc[13] ),
    .b(\adc_rd.ch1_prev[13] ),
    .y(_151_)
  );
  xci2_xnor2 _335_ (
    .a(\adc_rd.ch1_acc[5] ),
    .b(\adc_rd.ch1_prev[5] ),
    .y(_152_)
  );
  xci2_xnor2 _336_ (
    .a(\adc_rd.ch1_acc[6] ),
    .b(\adc_rd.ch1_prev[6] ),
    .y(_153_)
  );
  xci2_xnor2 _337_ (
    .a(\adc_rd.ch1_acc[12] ),
    .b(\adc_rd.ch1_prev[12] ),
    .y(_154_)
  );
  xci2_xnor2 _338_ (
    .a(\adc_rd.ch1_acc[11] ),
    .b(\adc_rd.ch1_prev[11] ),
    .y(_155_)
  );
  xci2_xnor2 _339_ (
    .a(\adc_rd.ch1_acc[10] ),
    .b(\adc_rd.ch1_prev[10] ),
    .y(_156_)
  );
  xci2_xnor2 _340_ (
    .a(\adc_rd.ch1_acc[20] ),
    .b(\adc_rd.ch1_prev[20] ),
    .y(_157_)
  );
  xci2_xnor2 _341_ (
    .a(\adc_rd.ch1_acc[23] ),
    .b(\adc_rd.ch1_prev[23] ),
    .y(_158_)
  );
  xci2_xnor2 _342_ (
    .a(\adc_rd.ch1_acc[16] ),
    .b(\adc_rd.ch1_prev[16] ),
    .y(_159_)
  );
  xci2_and2 _343_ (
    .a(_152_),
    .b(_159_),
    .y(_160_)
  );
  xci2_and3 _344_ (
    .a(_151_),
    .b(_154_),
    .c(_160_),
    .y(_161_)
  );
  xci2_xnor2 _345_ (
    .a(\adc_rd.ch1_acc[7] ),
    .b(\adc_rd.ch1_prev[7] ),
    .y(_162_)
  );
  xci2_xnor2 _346_ (
    .a(\adc_rd.ch1_acc[3] ),
    .b(\adc_rd.ch1_prev[3] ),
    .y(_163_)
  );
  xci2_xnor2 _347_ (
    .a(\adc_rd.ch1_acc[17] ),
    .b(\adc_rd.ch1_prev[17] ),
    .y(_164_)
  );
  xci2_and2 _348_ (
    .a(_163_),
    .b(_164_),
    .y(_165_)
  );
  xci2_and3 _349_ (
    .a(_153_),
    .b(_162_),
    .c(_165_),
    .y(_166_)
  );
  xci2_xnor2 _350_ (
    .a(\adc_rd.ch1_acc[9] ),
    .b(\adc_rd.ch1_prev[9] ),
    .y(_167_)
  );
  xci2_xnor2 _351_ (
    .a(\adc_rd.ch1_acc[18] ),
    .b(\adc_rd.ch1_prev[18] ),
    .y(_168_)
  );
  xci2_and3 _352_ (
    .a(_150_),
    .b(_155_),
    .c(_168_),
    .y(_169_)
  );
  xci2_and2 _353_ (
    .a(_167_),
    .b(_169_),
    .y(_170_)
  );
  xci2_and3 _354_ (
    .a(_161_),
    .b(_166_),
    .c(_170_),
    .y(_171_)
  );
  xci2_xnor2 _355_ (
    .a(\adc_rd.ch1_acc[19] ),
    .b(\adc_rd.ch1_prev[19] ),
    .y(_172_)
  );
  xci2_and2 _356_ (
    .a(_158_),
    .b(_172_),
    .y(_173_)
  );
  xci2_and3 _357_ (
    .a(_146_),
    .b(_148_),
    .c(_173_),
    .y(_174_)
  );
  xci2_xnor2 _358_ (
    .a(\adc_rd.ch1_acc[21] ),
    .b(\adc_rd.ch1_prev[21] ),
    .y(_175_)
  );
  xci2_and2 _359_ (
    .a(_149_),
    .b(_175_),
    .y(_176_)
  );
  xci2_xnor2 _360_ (
    .a(\adc_rd.ch1_acc[8] ),
    .b(\adc_rd.ch1_prev[8] ),
    .y(_177_)
  );
  xci2_and3 _361_ (
    .a(_157_),
    .b(_176_),
    .c(_177_),
    .y(_178_)
  );
  xci2_xnor2 _362_ (
    .a(\adc_rd.ch1_acc[1] ),
    .b(\adc_rd.ch1_prev[1] ),
    .y(_179_)
  );
  xci2_xnor2 _363_ (
    .a(\adc_rd.ch1_acc[4] ),
    .b(\adc_rd.ch1_prev[4] ),
    .y(_180_)
  );
  xci2_and3 _364_ (
    .a(_147_),
    .b(_179_),
    .c(_180_),
    .y(_181_)
  );
  xci2_and2 _365_ (
    .a(_156_),
    .b(_181_),
    .y(_182_)
  );
  xci2_and3 _366_ (
    .a(_174_),
    .b(_178_),
    .c(_182_),
    .y(_183_)
  );
  xci2_nand2 _367_ (
    .a(_171_),
    .b(_183_),
    .y(_061_)
  );
  xci2_dffcl _368_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_000_),
    .q(\adc_rd.shift_reg[0] )
  );
  xci2_dffcl _369_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_001_),
    .q(\adc_rd.shift_reg[1] )
  );
  xci2_dffcl _370_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_002_),
    .q(\adc_rd.shift_reg[2] )
  );
  xci2_dffcl _371_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_003_),
    .q(\adc_rd.shift_reg[3] )
  );
  xci2_dffcl _372_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_004_),
    .q(\adc_rd.shift_reg[4] )
  );
  xci2_dffcl _373_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_005_),
    .q(\adc_rd.shift_reg[5] )
  );
  xci2_dffcl _374_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_006_),
    .q(\adc_rd.shift_reg[6] )
  );
  xci2_dffcl _375_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_007_),
    .q(\adc_rd.shift_reg[7] )
  );
  xci2_dffcl _376_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_008_),
    .q(\adc_rd.shift_reg[8] )
  );
  xci2_dffcl _377_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_009_),
    .q(\adc_rd.shift_reg[9] )
  );
  xci2_dffcl _378_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_010_),
    .q(\adc_rd.shift_reg[10] )
  );
  xci2_dffcl _379_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_011_),
    .q(\adc_rd.shift_reg[11] )
  );
  xci2_dffcl _380_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_012_),
    .q(\adc_rd.shift_reg[12] )
  );
  xci2_dffcl _381_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_013_),
    .q(\adc_rd.shift_reg[13] )
  );
  xci2_dffcl _382_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_014_),
    .q(\adc_rd.shift_reg[14] )
  );
  xci2_dffcl _383_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_015_),
    .q(\adc_rd.shift_reg[15] )
  );
  xci2_dffcl _384_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_016_),
    .q(\adc_rd.shift_reg[16] )
  );
  xci2_dffcl _385_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_017_),
    .q(\adc_rd.shift_reg[17] )
  );
  xci2_dffcl _386_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_018_),
    .q(\adc_rd.shift_reg[18] )
  );
  xci2_dffcl _387_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_019_),
    .q(\adc_rd.shift_reg[19] )
  );
  xci2_dffcl _388_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_020_),
    .q(\adc_rd.shift_reg[20] )
  );
  xci2_dffcl _389_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_021_),
    .q(\adc_rd.shift_reg[21] )
  );
  xci2_dffcl _390_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_022_),
    .q(\adc_rd.shift_reg[22] )
  );
  xci2_dffcl _391_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_023_),
    .q(\adc_rd.shift_reg[23] )
  );
  xci2_dffcl _392_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_024_),
    .q(\adc_rd.bit_cnt[0] )
  );
  xci2_dffcl _393_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_025_),
    .q(\adc_rd.bit_cnt[1] )
  );
  xci2_dffcl _394_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_026_),
    .q(\adc_rd.bit_cnt[2] )
  );
  xci2_dffcl _395_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_027_),
    .q(\adc_rd.bit_cnt[3] )
  );
  xci2_dffcl _396_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_028_),
    .q(\adc_rd.bit_cnt[4] )
  );
  xci2_dffcl _397_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_029_),
    .q(\adc_rd.bit_cnt[5] )
  );
  xci2_dffcl _398_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_030_),
    .q(\adc_rd.wreg_mode )
  );
  xci2_dff _399_ (
    .clk(sclk),
    .d(_031_),
    .q(din)
  );
  xci2_dffcl _400_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_032_),
    .q(\adc_rd.state[0] )
  );
  xci2_dffcl _401_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_033_),
    .q(\adc_rd.state[1] )
  );
  xci2_dffcl _402_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_034_),
    .q(\adc_rd.state[2] )
  );
  xci2_dffcl _403_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_035_),
    .q(\adc_rd.work_mode )
  );
  xci2_dffcl _404_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_036_),
    .q(\adc_rd.ch1_acc[0] )
  );
  xci2_dffcl _405_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_037_),
    .q(\adc_rd.ch1_acc[1] )
  );
  xci2_dffcl _406_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_038_),
    .q(\adc_rd.ch1_acc[2] )
  );
  xci2_dffcl _407_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_039_),
    .q(\adc_rd.ch1_acc[3] )
  );
  xci2_dffcl _408_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_040_),
    .q(\adc_rd.ch1_acc[4] )
  );
  xci2_dffcl _409_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_041_),
    .q(\adc_rd.ch1_acc[5] )
  );
  xci2_dffcl _410_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_042_),
    .q(\adc_rd.ch1_acc[6] )
  );
  xci2_dffcl _411_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_043_),
    .q(\adc_rd.ch1_acc[7] )
  );
  xci2_dffcl _412_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_044_),
    .q(\adc_rd.ch1_acc[8] )
  );
  xci2_dffcl _413_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_045_),
    .q(\adc_rd.ch1_acc[9] )
  );
  xci2_dffcl _414_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_046_),
    .q(\adc_rd.ch1_acc[10] )
  );
  xci2_dffcl _415_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_047_),
    .q(\adc_rd.ch1_acc[11] )
  );
  xci2_dffcl _416_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_048_),
    .q(\adc_rd.ch1_acc[12] )
  );
  xci2_dffcl _417_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_049_),
    .q(\adc_rd.ch1_acc[13] )
  );
  xci2_dffcl _418_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_050_),
    .q(\adc_rd.ch1_acc[14] )
  );
  xci2_dffcl _419_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_051_),
    .q(\adc_rd.ch1_acc[15] )
  );
  xci2_dffcl _420_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_052_),
    .q(\adc_rd.ch1_acc[16] )
  );
  xci2_dffcl _421_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_053_),
    .q(\adc_rd.ch1_acc[17] )
  );
  xci2_dffcl _422_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_054_),
    .q(\adc_rd.ch1_acc[18] )
  );
  xci2_dffcl _423_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_055_),
    .q(\adc_rd.ch1_acc[19] )
  );
  xci2_dffcl _424_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_056_),
    .q(\adc_rd.ch1_acc[20] )
  );
  xci2_dffcl _425_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_057_),
    .q(\adc_rd.ch1_acc[21] )
  );
  xci2_dffcl _426_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_058_),
    .q(\adc_rd.ch1_acc[22] )
  );
  xci2_dffcl _427_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_059_),
    .q(\adc_rd.ch1_acc[23] )
  );
  xci2_dffcl _428_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_060_),
    .q(\adc_rd.start_mode )
  );
  xci2_dffcl _429_ (
    .clk(clk),
    .clr(rst_l),
    .d(_062_),
    .q(sclk)
  );
  xci2_dffcl _430_ (
    .clk(sclk),
    .clr(rst_l),
    .d(_061_),
    .q(ready_sample)
  );
  xci2_dffcl _431_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[0] ),
    .q(\adc_rd.ch1_prev[0] )
  );
  xci2_dffcl _432_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[1] ),
    .q(\adc_rd.ch1_prev[1] )
  );
  xci2_dffcl _433_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[2] ),
    .q(\adc_rd.ch1_prev[2] )
  );
  xci2_dffcl _434_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[3] ),
    .q(\adc_rd.ch1_prev[3] )
  );
  xci2_dffcl _435_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[4] ),
    .q(\adc_rd.ch1_prev[4] )
  );
  xci2_dffcl _436_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[5] ),
    .q(\adc_rd.ch1_prev[5] )
  );
  xci2_dffcl _437_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[6] ),
    .q(\adc_rd.ch1_prev[6] )
  );
  xci2_dffcl _438_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[7] ),
    .q(\adc_rd.ch1_prev[7] )
  );
  xci2_dffcl _439_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[8] ),
    .q(\adc_rd.ch1_prev[8] )
  );
  xci2_dffcl _440_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[9] ),
    .q(\adc_rd.ch1_prev[9] )
  );
  xci2_dffcl _441_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[10] ),
    .q(\adc_rd.ch1_prev[10] )
  );
  xci2_dffcl _442_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[11] ),
    .q(\adc_rd.ch1_prev[11] )
  );
  xci2_dffcl _443_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[12] ),
    .q(\adc_rd.ch1_prev[12] )
  );
  xci2_dffcl _444_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[13] ),
    .q(\adc_rd.ch1_prev[13] )
  );
  xci2_dffcl _445_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[14] ),
    .q(\adc_rd.ch1_prev[14] )
  );
  xci2_dffcl _446_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[15] ),
    .q(\adc_rd.ch1_prev[15] )
  );
  xci2_dffcl _447_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[16] ),
    .q(\adc_rd.ch1_prev[16] )
  );
  xci2_dffcl _448_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[17] ),
    .q(\adc_rd.ch1_prev[17] )
  );
  xci2_dffcl _449_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[18] ),
    .q(\adc_rd.ch1_prev[18] )
  );
  xci2_dffcl _450_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[19] ),
    .q(\adc_rd.ch1_prev[19] )
  );
  xci2_dffcl _451_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[20] ),
    .q(\adc_rd.ch1_prev[20] )
  );
  xci2_dffcl _452_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[21] ),
    .q(\adc_rd.ch1_prev[21] )
  );
  xci2_dffcl _453_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[22] ),
    .q(\adc_rd.ch1_prev[22] )
  );
  xci2_dffcl _454_ (
    .clk(sclk),
    .clr(rst_l),
    .d(\adc_rd.ch1_acc[23] ),
    .q(\adc_rd.ch1_prev[23] )
  );
  assign adc045_data = { \adc_rd.ch1_acc[23] , \adc_rd.ch1_acc[22] , \adc_rd.ch1_acc[21] , \adc_rd.ch1_acc[20] , \adc_rd.ch1_acc[19] , \adc_rd.ch1_acc[18] , \adc_rd.ch1_acc[17] , \adc_rd.ch1_acc[16] , \adc_rd.ch1_acc[15] , \adc_rd.ch1_acc[14] , \adc_rd.ch1_acc[13] , \adc_rd.ch1_acc[12] , \adc_rd.ch1_acc[11] , \adc_rd.ch1_acc[10] , \adc_rd.ch1_acc[9] , \adc_rd.ch1_acc[8] , \adc_rd.ch1_acc[7] , \adc_rd.ch1_acc[6] , \adc_rd.ch1_acc[5] , \adc_rd.ch1_acc[4] , \adc_rd.ch1_acc[3] , \adc_rd.ch1_acc[2] , \adc_rd.ch1_acc[1] , \adc_rd.ch1_acc[0]  };
  assign nRST = rst_l_adc;
  assign start = hard_start;
endmodule
