create_clock -name bb_clk_in -period 82 -waveform {0 41} [get_ports bb_clk_in]
set_false_path -from [get_ports rst_l] -to [all_outputs]
set_false_path -from [get_ports rst_l] -to [all_registers]
set_false_path -from [all_inputs]
set_false_path -to [all_outputs]